apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    url: ${INFLUXDB_URL}
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
